vim.keymap.set({ "n", "v" }, "H", "0", { desc = "Jump to line start" })
vim.keymap.set({ "n", "v" }, "L", function()
  local col = vim.fn.col("$")
  vim.fn.cursor(0, col)
end, { desc = "Jump past line end" })
vim.keymap.set({ "n", "v" }, "J", "G", { desc = "Jump to file end" })
vim.keymap.set({ "n", "v" }, "K", "gg", { desc = "Jump to file start" })
vim.keymap.set({ "n", "v" }, "<M-l>", "w", { desc = "Next word" })
vim.keymap.set({ "n", "v" }, "<M-h>", "b", { desc = "Previous word" })

vim.keymap.set("n", "<M-H>", "<cmd>bprev<cr>", { desc = "Previous buffer" })
vim.keymap.set("n", "<M-L>", "<cmd>bnext<cr>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader>e", "<C-w>l", { desc = "Focus right split" })

vim.keymap.set("n", "<leader>v", "ggVG", { desc = "Select all" })
vim.keymap.set({ "n", "v" }, "<leader>J", "J", { desc = "Join lines" })
vim.keymap.set("n", "<leader>k", vim.lsp.buf.hover, { desc = "Hover docs" })
vim.keymap.set("i", "jk", "<Esc>", { desc = "Exit insert mode" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
vim.keymap.set("n", "<leader>b", "<cmd>make<cr>", { desc = "Build (make)" })
vim.keymap.set("n", "<leader>x", function()
  vim.ui.open(vim.fn.expand("%:p"))
end, { desc = "Open file in system app" })

vim.keymap.set("n", "s", "<Nop>", { desc = "Disabled" })
vim.keymap.set("n", "S", "<Nop>", { desc = "Disabled" })
vim.keymap.set("n", "q", "<Nop>", { desc = "Disabled" })
vim.keymap.set("n", "Q", "<Nop>", { desc = "Disabled" })

vim.api.nvim_create_user_command("Q", "qall!", {})
